Fix ValueError: invalid literal for int() with base 16
The `identifier()` function previously returned the serial number separated with an underscore "_", whereas `BrotherQLBackendPyUSB.__init__()` expects the device_specifier to separate the serial number with a forward slash "/". This was causing the following error to be raised when a serial number is present for the printer:

    ValueError: invalid literal for int() with base 16